# -*- coding: utf-8 -*-
import numpy

import pyscf.gto
import pyscf.scf
import pyscf.pbc.gto
import pyscf.pbc.scf

import torch
from torch import Tensor
from torch.autograd import Function
from torch.autograd.function import once_differentiable

from mlmsdft.dft.integrals import RangeSeparatedIntegralCache


class _HartreeFunctionalAO(Function):
    """
    The Hartree energy is the interaction of a classical charge density with itself.
    There is no equivalent of the Hartree term in the multistate density functional
    formalism, because the Hartree part of the Coulomb energy does not correspond to
    an operator. We can define a functional of the matrix density D(r) that reduces
    to the Hartree energy in the case of a single electronic state, which is an
    analytical functional and transforms correctly under basis transformations U,
    i.e. `U⁻¹ J[D(r)] U = J[U⁻¹ D(r) U]` :

        J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∫∫' Dᵢₖ(r) Dₖⱼ(r')/|r-r'|

    where Dᵢⱼ(r) is the electronic density of the state Ψᵢ, Dᵢᵢ(r) = ρᵢ(r),
    or the transition density between the states Ψᵢ and Ψⱼ, Dᵢⱼ(r).

    If there are multiple electronic state, the diagonals J[D(r)]ᵢᵢ differ from the
    classical Coulomb interaction of the state density of state i with itself, because
    the matrix product ∑ₖDᵢₖ(r) Dₖⱼ(r') mixes in transition densities to other
    states k≠i.

    The matrix density is represented in a basis of atomic orbitals as

        Dᵢⱼ(X,x; r) = ∑ᵦ ∑ᵧ Dᵦᵧᵢⱼ(X,x) 𝛘ᵦ(r) 𝛘ᵧ(r)
    """
    @staticmethod
    def forward(ctx, density_matrices_ao: Tensor, mol: pyscf.gto.Mole) -> Tensor:
        """
        Compute the Hartree-like part of the electron-electronc repulsion
        using the AO representation of the matrix density,

            J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∑ᵦ ∑ᵧ Dᵦᵧᵢₖ Vᵦᵧ[Dₖⱼ],

        where

            Vᵦᵧ[Dₖⱼ] = ∫ 𝛘ᵦ(r) (∫' Dₖⱼ(r')/|r-r'|) 𝛘ᵧ(r)

        is the electrostatic potential generated by the (transition) density matrix Dₖⱼ(r)
        sandwiched between the atomic orbitals 𝛘ᵦ and 𝛘ᵧ.

        :param density_matrices_ao: state (i==j) and transition (i != j) density matrices in
            in the AO basis summed over spin, density_matrices_ao[b,g,i,j] = Dᵦᵧᵢⱼ = Dᵅᵦᵧᵢⱼ+Dᵝᵦᵧᵢⱼ
        :type density_matrices_ao: Tensor of shape (Nbasis,Nbasis,Nstate,Nstate)

        :param mol: molecule with atomic coordinates and basis set
        :type mol: pyscf.gto.Mole

        :return hartree_like_matrix: The Hartree-like matrix Jᵢⱼ in the subspace
           of the electronic states i,j=1,...,nstate
        :rtype hartree_like_matrix: Tensor of shape (Nstate,Nstate)
        """
        # Convert matrix density to a list of numpy AO density matrices
        # [D00, D01, D02, ...]
        nbasis, nbasis, nstate, nstate = density_matrices_ao.size()
        dms = []
        for i in range(0, nstate):
            for j in range(i, nstate):
                # Since the matrix density is symmetric, we only have
                # to compute the electrostatic potential for the densities
                # and transition densities in the upper triangle (i <= j).
                dms.append(density_matrices_ao[:,:,i,j].cpu().numpy())

        # Compute the Hartree potentials for all (transition) densities in the
        # matrix density using pyscf (J-build).
        #
        #    V_{a,b}[Dᵢⱼ] = ∑_{c,d} (ab|cd) D_{c,d,i,j}
        #
        # where (ab|cd) are the electron repulsion integrals for the basis functions
        # a,b,c,d and i,j are state labels.
        if isinstance(mol, pyscf.pbc.gto.cell.Cell):
            # `mol` is a periodic crystal
            vjs = pyscf.pbc.scf.hf.get_j(
                mol, dms,
                # at the Gamma point
                kpt=numpy.array([0.0, 0.0, 0.0]))
        else:
            # `mol` is a molecule
            vjs, _ = pyscf.scf.hf.get_jk(
                mol, dms, with_j=True, with_k=False)

        # Convert Hartree potentials V[D] back to pytorch tensor.
        hartree_potentials = numpy.zeros((nbasis, nbasis, nstate, nstate))
        # Iterate over list of electrostatic potentials and put them
        # back into matrix form.
        vjs = iter(vjs)
        for i in range(0, nstate):
            for j in range(i, nstate):
                vj = next(vjs)
                hartree_potentials[:,:,i,j] = vj
                if i != j:
                    # The matrix density is symmetric and so is the electrostatic potential.
                    hartree_potentials[:,:,j,i] = vj

        # hartree_potentials_ao[b,g,i,j] = Vᵦᵧ[Dᵢⱼ]
        hartree_potentials_ao = torch.from_numpy(hartree_potentials).to(
            dtype=density_matrices_ao.dtype, device=density_matrices_ao.device)

        # Hartree potentials are needed for backpropagation.
        ctx.save_for_backward(hartree_potentials_ao)

        # Compute J[D(r)]ᵢⱼ = 1/2 ∑ₖ ∑ᵦ ∑ᵧ Dᵦᵧᵢₖ Vᵦᵧ[Dₖⱼ]
        hartree_like_matrix = 0.5 * torch.einsum('bgik,bgkj->ij', density_matrices_ao, hartree_potentials_ao)

        return hartree_like_matrix

    @staticmethod
    @once_differentiable
    def backward(ctx, grad_output: Tensor) -> Tensor:
        """
        Compute gradients w/r/t inputs using chain rule

        :param grad_output: vector xᵢⱼ = ∂g/∂Jᵢⱼ, gradient with respect to outputs of J[D(r)]ᵢⱼ
        :type grad_output: Tensor of size (Nstate,Nstate)

        :return grad_input: ∂g/∂Dᵦᵧₘₙ gradient with respect to D[b,g,m,n], i.e. the inputs of J
        :rtype grad_input: Tensor of size (Nbasis,Nbasis,Nstate,Nstate)
        """
        hartree_potentials_ao, = ctx.saved_tensors
        # chain rule
        # ∑ᵢ∑ⱼ ∂Jᵢⱼ/∂Dᵦᵧₘₙ xᵢⱼ = 1/2 ∑ⱼ (xₘⱼ Vᵦᵧⱼₙ + Vᵦᵧₘⱼ xⱼₙ)
        grad_input = 0.5 * (
            torch.einsum('mj,bgjn->bgmn', grad_output, hartree_potentials_ao) +
            torch.einsum('bgmj,jn->bgmn', hartree_potentials_ao, grad_output))

        # There is no gradient w/r/t the second argument `mol`, therefore None is returned.
        return grad_input, None


class HartreeFunctionalAO(torch.nn.Module):
    """ see doc-string for _HartreeFunctionalAO """
    def __init__(self, mol: pyscf.gto.Mole):
        super().__init__()
        self.mol = mol
    def forward(self, density_matrices_ao: Tensor) -> Tensor:
        return _HartreeFunctionalAO.apply(density_matrices_ao, self.mol)


class _HartreeFunctionalERI(Function):
    """Differentiable Hartree-like contraction for a fixed ERI tensor."""

    @staticmethod
    def forward(ctx, density_matrices_ao: Tensor, eri_ao: Tensor) -> Tensor:
        # V_ab,kj = (ab|cd) D_cd,kj and
        # J_ij = 1/2 D_ab,ik V_ab,kj.
        potential = torch.einsum("abcd,cdij->abij", eri_ao, density_matrices_ao)
        ctx.save_for_backward(potential)
        return 0.5 * torch.einsum("abik,abkj->ij", density_matrices_ao, potential)

    @staticmethod
    @once_differentiable
    def backward(ctx, grad_output: Tensor):
        (potential,) = ctx.saved_tensors
        grad_density = 0.5 * (
            torch.einsum("mj,abjn->abmn", grad_output, potential) +
            torch.einsum("abmj,jn->abmn", potential, grad_output)
        )
        return grad_density, None


class HartreeFunctionalShortRangeAO(torch.nn.Module):
    """Hartree complement using the erfc short-range kernel."""

    def __init__(self, mol: pyscf.gto.Mole, omega: float):
        super().__init__()
        self.integrals = RangeSeparatedIntegralCache(mol, omega)

    @property
    def omega(self) -> float:
        return self.integrals.omega

    def forward(self, density_matrices_ao: Tensor) -> Tensor:
        eri = self.integrals.eri_ao("short_range").to(
            dtype=density_matrices_ao.dtype,
            device=density_matrices_ao.device,
        )
        return _HartreeFunctionalERI.apply(density_matrices_ao, eri)
